# Generated by Django 5.0 on 2025-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_type',
            field=models.CharField(choices=[('none', 'Нет'), ('parking_space', 'Паркоместо'), ('garage', 'Гараж')], default='none', max_length=20, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Улица'),
        ),
    ]
