# Generated by Django 5.0 on 2025-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_location_listing_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB'), ('UAH', 'UAH')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
    ]
