# Generated by Django 5.0 on 2025-12-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingviewstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingviewstat',
            name='id',
        ),
        migrations.AlterField(
            model_name='listingviewstat',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='view_stat', serialize=False, to='listings.listing'),
        ),
    ]
