# Generated by Django 5.0 on 2026-06-22 09:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_amenity_listing_bathrooms_listing_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='instant_book',
            field=models.BooleanField(default=False, verbose_name='Мгновенное бронирование'),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_nights',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Мин. ночей'),
        ),
        migrations.AddField(
            model_name='listing',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Комиссия платформы (%)'),
        ),
        migrations.CreateModel(
            name='ListingBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.listing', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Заблокированная дата',
                'verbose_name_plural': 'Заблокированные даты',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='listingblockeddate',
            constraint=models.UniqueConstraint(fields=('listing', 'date'), name='unique_listing_blocked_date'),
        ),
    ]
